### ISSUE TITLE
Copy-ToAllServers not working with Exchange 2016 servers

### ISSUE THREAD

**Issue by TontonLud** [Apoc70/Copy-ReceiveConnector#3]
Hello,

Copy-ToAllServers commutator doesn't work with Exchange 2016 server as ServerRole returned value is Mailbox.

Maybe you have to test on line 294 if ServerRole is Mailbox or ClientAccess

https://github.com/Apoc70/Copy-ReceiveConnector/blob/9f8f93ac5135cd85548c6e5fcc25a730f5d18e94/Copy-ReceiveConnector.ps1#L294

`$frontendServers = Get-ExchangeServer | Where-Object{($_.AdminDisplayVersion.Major -ge 15) -and ((([string]$_.ServerRole).Contains('Mailbox')) -or (([string]$_.ServerRole).Contains('Mailbox'))) -and ($_.Name -ne $SourceServer)} | Sort-Object Name
`

Regards,

**Comment by Apoc70** [comment]
Thanks. I will check that issue in the next few days.
