### ISSUE TITLE
Make ""update existing" a command line option to allow automated usage

### ISSUE THREAD

**Issue by verukins** [Apoc70/Copy-ReceiveConnector#6]
More of a request than an issue.... make update existing a commandline option (as well as user prompt) to allow for automated usage

**Comment by Apoc70** [comment]
Thanks for the request. I will give this a thought on how to implement this.

**Comment by verukins** [comment]
Hi.... ended up adding

[switch] $UpdateExisting 

and

if (($UpdateExisting) -OR `
          ((Request-Choice -Caption ('Do you want to UPDATE the receive connector {0} on server {1}?' -f $ConnectorName, $TargetServerName)) -eq 0)) { 

im not great at PS... so happy to take your advice.... but the above changes got me through my immediate requirement
